### 1. The anonymous or <b>lambda</b> functions are a way of writing functions consisting of a single statement returning the value.  These functions are defined with the <b>lambda</b> keyword, which has no meaning other than "we are declaring an anonymous function". For example, the following function squaring the input value:
    def square_function(x):
        return x**2
<p>
    Execute this function to square 3 and display the result:

In [9]:
def square_function(x):
    return x**2

In [14]:
print('The result of square function =', square_function(3))

The result of square function = 9


### Write the equivalent <b>lambda</b> function, execute it to square 3, and disply the result:

In [15]:
# Define the lambda function
square_function = lambda x: x**2

# Execute the function to square 3
result = square_function(3)

# Display the result
print(result)


9


### 2. Flatten an array with four methods: <b>reshape</b>, <b>resize</b>, <b>flatten</b>, and <b>ravel</b>. For each method, create a 3-by-4 array named "powers" containing the first 12 powers of 4 beginning with 4<sup>0</sup>, flatten the array and assign this flattened array to "flattened", display the result of "flattened" and then display the original array to show whether it was modified or unmodified, modify the first element of "flattened" to 10 and display results of "flattened" and the original array "powers" to show whether it was modified or unmodified.

In [2]:
import numpy as np

In [48]:
import numpy as np

print('Create a 3-by-4 array named "powers" containing the first 12 powers of 4')
powers = np.array([4**i for i in range(12)]).reshape(3, 4)
print("\nOriginal array:\n",powers)
# Flatten using reshape
flattened_reshape = powers.reshape(-1)
print("\nFlattened (reshape):\n", flattened_reshape)
print("\nOriginal array (after reshape):\n", powers)

# Flatten using flatten
flattened_flatten = powers.flatten()
print("\nFlattened (flatten):\n", flattened_flatten)
print("\nOriginal array (after flatten):\n", powers)

# Flatten using ravel
flattened_ravel = powers.ravel()
print("\nFlattened (ravel):\n", flattened_ravel)
print("\nOriginal array (after ravel):\n", powers)

# Modify the first element of "flattened_ravel"
flattened_ravel[0] = 10
print("\nModified flattened (ravel):\n", flattened_ravel)
print("\nOriginal array (after modifying flattened):\n", powers)


Create a 3-by-4 array named "powers" containing the first 12 powers of 4

Original array:
 [[      1       4      16      64]
 [    256    1024    4096   16384]
 [  65536  262144 1048576 4194304]]

Flattened (reshape):
 [      1       4      16      64     256    1024    4096   16384   65536
  262144 1048576 4194304]

Original array (after reshape):
 [[      1       4      16      64]
 [    256    1024    4096   16384]
 [  65536  262144 1048576 4194304]]

Flattened (flatten):
 [      1       4      16      64     256    1024    4096   16384   65536
  262144 1048576 4194304]

Original array (after flatten):
 [[      1       4      16      64]
 [    256    1024    4096   16384]
 [  65536  262144 1048576 4194304]]

Flattened (ravel):
 [      1       4      16      64     256    1024    4096   16384   65536
  262144 1048576 4194304]

Original array (after ravel):
 [[      1       4      16      64]
 [    256    1024    4096   16384]
 [  65536  262144 1048576 4194304]]

Modified flattened (

In [44]:
# Now modify the first element of each flattened array to 10
flattened_reshape[0] = 10
flattened_resize[0] = 10
flattened_flatten[0] = 10
flattened_ravel[0] = 10

# Display the results of the flattened arrays and the original "powers" array after modification
print("\nOriginal 'powers' array after modification:")
print(powers)
print("\nFlattened with reshape after modification:")
print(flattened_reshape)
print("\nFlattened with resize after modification:")
print(flattened_resize)
print("\nFlattened with flatten after modification:")
print(flattened_flatten)
print("\nFlattened with ravel after modification:")
print(flattened_ravel)


Original 'powers' array after modification:
[[     10       4      16      64]
 [    256    1024    4096   16384]
 [  65536  262144 1048576 4194304]]

Flattened with reshape after modification:
[     10       4      16      64     256    1024    4096   16384   65536
  262144 1048576 4194304]

Flattened with resize after modification:
[     10       4      16      64     256    1024    4096   16384   65536
  262144 1048576 4194304]

Flattened with flatten after modification:
[     10       4      16      64     256    1024    4096   16384   65536
  262144 1048576 4194304]

Flattened with ravel after modification:
[     10       4      16      64     256    1024    4096   16384   65536
  262144 1048576 4194304]


### 3 Python Pandas DataFrame

### (a) Create a Pandas DataFrame containing the following information:
<pre>
   Name  Score  Year
Vanessa    100  Junior
   Nick     95  Senior
   Jack     69  Junior
 Olivia     88  Senior
</pre>
This is the original DataFrame.

In [50]:
import pandas as pd

# Create a DataFrame with the given information
data = {
    'Name': ['Vanessa', 'Nick', 'Jack', 'Olivia'],
    'Score': [100, 95, 69, 88],
    'Year': ['Junior', 'Senior', 'Junior', 'Senior']
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)


      Name  Score    Year
0  Vanessa    100  Junior
1     Nick     95  Senior
2     Jack     69  Junior
3   Olivia     88  Senior


### (b) Create a DataFrame named temp by including only the columns Name and Score in two different ways, with one way using the loc operator. Display the results of temp.

In [54]:
# Method 1: Selecting the columns directly by specifying them
temp_1 = df[['Name', 'Score']]

# Method 2: Using the loc operator to select the columns
temp_2 = df.loc[:, ['Name', 'Score']]

# Display both results
print(temp_1)
print()
print(temp_2)

      Name  Score
0  Vanessa    100
1     Nick     95
2     Jack     69
3   Olivia     88

      Name  Score
0  Vanessa    100
1     Nick     95
2     Jack     69
3   Olivia     88


### (c) Create a DataFrame named temp2 from temp by including only data for Vanessa and Olivia using the iloc operator. Display the result of temp2.

In [72]:


# Using the iloc operator to select the rows for Vanessa and Olivia
temp2 = temp_1.iloc[[0, 3]]  # Row indices 0 and 3 correspond to Vanessa and Olivia

# Display the result
print(temp2)


      Name  Score
0  Vanessa    100
3   Olivia     88


### (d) Create a DataFrame named temp3 from the original DataFrame by including only the data for Vanessa and Olivia using the iloc operator.

In [71]:
# Using the iloc operator to select the rows for Vanessa and Olivia from the original DataFrame
temp3 = df.iloc[[0, 3]]  # Row indices 0 and 3 correspond to Vanessa and Olivia

# Display the result
print(temp3)


      Name  Score    Year
0  Vanessa    100  Junior
3   Olivia     88  Senior


### (e) Use the describe method to produce descriptive statistics of score in the original DataFrame. 

In [73]:
df.describe()

Score
count    4.000000
mean    88.000000
std     13.589211
min     69.000000
25%     83.250000
50%     91.500000
75%     96.250000
max    100.000000

### (f) Sort original DataFrame by Score in descending order. Display the sorted DataFrame.

In [74]:
# Sorting the original DataFrame by Score in descending order
sorted_df = df.sort_values(by='Score', ascending=False)

# Display the sorted DataFrame
print(sorted_df)


      Name  Score    Year
0  Vanessa    100  Junior
1     Nick     95  Senior
3   Olivia     88  Senior
2     Jack     69  Junior
